apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e2e-tests-java-springboot-johbtiom
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/e2e-tests-java-springboot-johbtiom:a2f7e890bef977a625afc9eff0beb82834f4787f
          name: container-image
